# Optional pre-commit hooks that could be problematic if run automatically (e.g. because they mostly fail)
  # but it's still useful to see the output or produce automatic fixes at specific times
# To run these hooks, call `pre-commit run [hook_id] --config ./.pre-commit-optional.yaml`
  # omitting `[hook_id]` will run all hooks in the below configuration

repos:
  - repo: local
    hooks:
      # Run the parser on sample input
      # TODO: move this to the main pre-commit config (unless the parser is completely failing and throwing an error)
        # make sure this hook goes on top (before the hooks like check-json and validation of output with the schema)
      - id: convert-test-input
        name: convert-test-input
        description: Run parser on sample input data
        # TODO: make sure the input_dir, output_dir, and validate args are set up with argparse in the script
        entry: 'python -m antibody_annotation_to_json.cli --input_dir=test/input_data/ --output_dir=test/json_files/
        --validate doc/INN_antibody_schema.json'
        language: system
        files: '^(test/input_data/.+\.txt)$|/cli.py$|/core.py$|^doc/.*schema\.json$'
        pass_filenames: false
      # validation is already performed within the parser/converter, but this hook provides slightly different output,
      # and can be used on sample output data without having to provide input data and run the parser;
      # this is useful for exploring the schema's validation behaviour on manually written/edited json files
      - id: validate-json-files
        name: validate-json-files
        description: Validate JSON output (generated by the parse-samples hook) against the schema
        entry: jsonschema validate ./doc/INN_antibody_schema.json ./test/json_files/
        args: [ --trace ]
        language: system
        files: '^test/json_files/.+\.json$'
        pass_filenames: false
      # TODO: add a local system hook for the command-line execution of python unittest
        # might need to use `python -m unittest discover` to ensure the package root is added to sys.path and relative
          # imports work; might also need the `-p` option after the discover subcommand
        # log unittest's output (just one log file that's overwritten for every commit)
          # this can be done with the 'log_file' key in the hook config
        # once the parser is stable (passing the tests), move the hook to the main pre-commit config
