# Optional pre-commit hooks that could be problematic if run automatically (e.g. because they mostly fail)
  # but it's still useful to see the output or produce automatic fixes at specific times
# To run these hooks, call `pre-commit run [hook_id] --config ./.pre-commit-optional.yaml`
  # omitting `[hook_id]` will run all hooks in the below configuration

repos:
  - repo: local
    hooks:
      # Run the parser on sample input
      # TODO: move this to the main pre-commit config (unless the parser is completely failing and throwing an error)
        # make sure this hook goes on top (before the hooks like check-json and validation of output with the schema)
      - id: parse-samples
        name: parse-samples
        description: Run parser on sample input data (output data is subsequently validated by other hooks)
        # TODO: `python3` only works for linux, so find a way to make it cross-platform compatible
        # TODO: make sure the input_dir and output_dir args are set up with argparse in the script
        entry: python3 -m runner --input_dir=test/input_data/ --output_dir=test/json_files/
        language: system
        files: '^(test/input_data/.+\.txt)|(cli.py)|(core.py)$'
        pass_filenames: false
      - id: validate-json-files
        name: validate-json-files
        description: Validate JSON output (generated by the parse-samples hook) against the schema
        entry: jsonschema validate ./doc/INN_antibody_schema.json
        language: system
        files: '^test/json_files/.+\.json$'
      # TODO: add a local system hook for the command-line execution of python unittest
        # log unittest's output (just one log file that's overwritten for every commit)
          # this can be done with the 'log_file' key in the hook config
        # once the parser is stable (passing the tests), move the hook to the main pre-commit config
