# STATUS: archived / kept for reference (as a template for similar workflows to put in the <REPO>/.github/workflows/ directory)
# REASON: the documentation tool json-schema-for-humans is inadequate for representing our schema
#   - patternProperties are not displayed in the html output
#   - subschemas for array items are not displayed in the html output
#
# ###########################################

name: Generate JSON Schema Documentation

on:
  push:
    paths:
      - "doc/INN_Antibodies_schema.json"  # Trigger workflow when the JSON Schema is updated
  pull_request:
    paths:
      - "doc/INN_Antibodies_schema.json"  # Trigger workflow for pull requests that update the JSON Schema

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Step 3: Install dependencies
      - name: Install json-schema-for-humans
        run: |
          pip install json-schema-for-humans

      # Step 4: Generate human-readable HTML
      - name: Generate human-readable JSON Schema
        run: |
          generate-schema-doc doc/INN_Antibodies_schema.json doc/INN_Antibodies_json_schema_for_humans.html --config template_name=js

      # Step 5: Commit and push changes (if needed)
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add doc/INN_Antibodies_json_schema_for_humans.html
          git commit -m "Auto-generate JSON Schema documentation"
          git push


# TODO: on the same actions (update to JSON Schema), run another job that validates the schema itself
  # this makes sure there are no typos or structural issues which could cause unwanted and confusing validation errors
  # example python code:  
    # from jsonschema import Draft202012Validator
    # import json
    # schema = json.load("path/to/schema")
    # Draft202012Validator.check_schema(schema)
    # print("Schema is valid!")
      # TODO: replace the above line with writing to a log file or a README file, or opening a GitHub issue repository
  # or better: use the command-line tool check-jsonschema (which automatically gets the metaschema from $schema)
    # check-jsonschema --check-metaschema my_schema.json
# TODO: and a third job: unit testing the schema with test cases (this should be triggered on updates to the relevant test files as well as the schema)
# TODO: are these 3 jobs best in a separate yml file / github actions workflow?
  # if not separate (all in this file), make sure to change the file name and the "name" line at the top
# NOTE: the GitHub Actions workflows for validation & testing could also be run as pre-commit hooks, which would give the opportunity to correct any validation failures/errors before committing and pushing; the GitHub workflows could still run, but maybe without making a commit if the validation/testing passes

          
